-- _____________________________________________________________________________________________________________________
-- BEGIN SCHEMA
-- _____________________________________________________________________________________________________________________


SET AUTOCOMMIT = 0;
START TRANSACTION;

-- Dropping DB (for reloading purpose):
DROP SCHEMA IF EXISTS nycflights13;

-- Creating DB with its encoding:
CREATE SCHEMA nycflights13 CHARACTER SET utf8mb4 -- utf8 is an alias for utf8mb3 and will be for utf8mb4 for MySQL futur releases.
     DEFAULT COLLATE utf8mb4_0900_ai_ci; 
                                                   
-- Connecting to the DB:
USE nycflights13 ;

-- _____________________________________________________________________________________________________________________
-- CREATING MAIN TABLES
-- _____________________________________________________________________________________________________________________ 

-- Creating table flights:
DROP TABLE IF EXISTS flights;
CREATE TABLE flights 
(
     year SMALLINT UNSIGNED,
     month TINYINT UNSIGNED,
     day TINYINT UNSIGNED,
     dep_time SMALLINT UNSIGNED,
     sched_dep_time SMALLINT UNSIGNED,
     dep_delay SMALLINT,
     arr_time SMALLINT UNSIGNED,
     sched_arr_time SMALLINT UNSIGNED,
     arr_delay SMALLINT,
     carrier CHAR(2),
     flight SMALLINT UNSIGNED,
     tailnum CHAR(6) REFERENCES planes(tailnum),
     origin CHAR(3),
     dest CHAR(3),
     air_time SMALLINT UNSIGNED,
     distance SMALLINT UNSIGNED,
     hour TINYINT UNSIGNED,
     minute TINYINT UNSIGNED,
     time_hour DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 
SHOW WARNINGS; -- To display possible errors/warnings generated by the last request.


-- Creating table airlines:
DROP TABLE IF EXISTS airlines;
CREATE TABLE airlines 
(
     carrier CHAR(2) PRIMARY KEY,
     name CHAR(30)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 
SHOW WARNINGS;
-- .....................................................................................................................

-- Creating table planes:
DROP TABLE IF EXISTS planes;
CREATE TABLE planes 
(
 tailnum CHAR(6) PRIMARY KEY,
 year SMALLINT UNSIGNED,
 type CHAR(25),
 manufacturer CHAR(30),
 model CHAR(20),
 engines TINYINT,
 seats SMALLINT UNSIGNED,
 speed SMALLINT UNSIGNED,
 engine CHAR(15)    
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 
SHOW WARNINGS;
-- .....................................................................................................................

-- Creating table airports:
DROP TABLE IF EXISTS airports;
CREATE TABLE airports 
(
     faa CHAR(3) PRIMARY KEY,
     name CHAR(55),
     lat DECIMAL(18,15),
     lon DECIMAL(18,15),
     alt SMALLINT,
     tz TINYINT,
     dst CHAR(1),
     tzone CHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 
SHOW WARNINGS;
-- .....................................................................................................................

-- Creating table weather:
DROP TABLE IF EXISTS weather;
CREATE TABLE weather 
(
     origin CHAR(3),
     year SMALLINT UNSIGNED,
     month TINYINT UNSIGNED,
     day TINYINT UNSIGNED,
     hour TINYINT UNSIGNED,
     temp DECIMAL(5,2),
     dewp DECIMAL(5,2),
     humid DECIMAL(5,2),
     wind_dir SMALLINT UNSIGNED,
     wind_speed DECIMAL(25,20),
     wind_gust DECIMAL(20,15),
     precip DECIMAL(3,2),         --
     pressure DECIMAL(8,4),
     visib DECIMAL(4,2),
     time_hour DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 
SHOW WARNINGS;

-- _____________________________________________________________________________________________________________________
-- CREATING ADDITIONAL TABLES
-- _____________________________________________________________________________________________________________________

-- Creating table plane_models:
DROP TABLE IF EXISTS plane_models;
CREATE TABLE plane_models 
(
     model CHAR(20),
     engines TINYINT,
     seats SMALLINT UNSIGNED,
     speed SMALLINT UNSIGNED,
     type CHAR(25),
     engine CHAR(15),
     manufacturer CHAR(30)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 
SHOW WARNINGS;
-- .....................................................................................................................

-- Creating table model_types:
DROP TABLE IF EXISTS model_types;
CREATE TABLE model_types 
(
     type CHAR(25)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 
SHOW WARNINGS;
-- .....................................................................................................................

-- Creating table model_engines:
DROP TABLE IF EXISTS model_engines;
CREATE TABLE model_engines
(
     engine CHAR(15)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ; 
SHOW WARNINGS;
-- .....................................................................................................................

-- Creating table model_manufacturers:
DROP TABLE IF EXISTS model_manufacturers;
CREATE TABLE model_manufacturers
(
     manufacturer CHAR(30)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 
SHOW WARNINGS;
-- .....................................................................................................................

-- Creating table time_zone:
DROP TABLE IF EXISTS time_zone;
CREATE TABLE time_zone
(
     tzone CHAR(20),
     tz TINYINT,
     dst CHAR(1)
     
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 
SHOW WARNINGS;
-- .....................................................................................................................

SET AUTOCOMMIT = 1;

-- _____________________________________________________________________________________________________________________
-- END OF SCHEMA
-- _____________________________________________________________________________________________________________________